name: Compile PDFs
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Install LaTeX
        run: sudo apt-get install texlive texlive-lang-german texlive-pictures texlive-latex-extra

      - name: Compile Krypto-Vortrag
        run: cd Kryptowaehrungen; pdflatex slides.tex

      - name: 'Upload Krypto-Vortrag PDF'
        uses: actions/upload-artifact@v4
        with:
          name: Kryptowaehrungen.pdf
          path: Kryptowaehrungen/slides.pdf
          retention-days: 5