name: Compile PDFs
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Install LaTeX
        run: sudo apt-get install texlive texlive-lang-german texlive-pictures texlive-latex-extra latexmk

      - name: Compile slides
        run: make package

      - name: Upload slides
        uses: actions/upload-artifact@v4
        with:
          name: Slides
          path: slides
          retention-days: 14